---
title: "Harvest Information Program Download Cycle Shiny Report"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_depth: 3
    number_sections: true
    theme: cerulean
runtime: shiny
params:
  comp_path:
    value: x
---

```{r libs, include = FALSE}
library(tidyverse)
library(DT)
library(shiny)
```

```{r import, include = FALSE}

dl_data <- read_hip(params$comp_path)

cleaned_data <- clean(dl_data)

# Remove original data to improve memory use
rm(dl_data)
```

## Duplicates

### Before fixDuplicates (all 49 states)

```{r b_fd, echo = FALSE}
findDuplicates(cleaned_data)
```

### Before fixDuplicates (pick a state)

```{r b_fd_s, echo = FALSE}
dl_states <-
  cleaned_data %>% 
  select(dl_state) %>% 
  distinct() %>% 
  pull()

shinyApp(

  ui = fluidPage(
    selectInput("dl_state", "State:",
                choices = dl_states),
    plotOutput("findDuplicatesPlot")
  ),

  server = function(input, output) {
    output$findDuplicatesPlot = renderPlot({
      
      cleaned_data %>%
        # Filter to input state
        filter(dl_state == input$dl_state) %>% 
        # Create a row key
        mutate(hunter_key = paste0("hunter_", row_number())) %>%
        # Group by registrant information; name, city, state, birthday, dl_state
        group_by(
          firstname,
          lastname,
          city,
          state,
          birth_date,
          dl_state) %>%
        # Identify duplicates
        mutate(
          duplicate =
            ifelse(
              n() > 1,
              "duplicate",
              "1")) %>%
        ungroup() %>%
        # Filter out non-duplicate records
        filter(duplicate == "duplicate") %>%
        # Sort tibble
        arrange(
          firstname,
          lastname,
          city,
          state,
          birth_date,
          dl_state) %>%
        select(-c("hunter_key", "duplicate")) %>%
        group_by(firstname, lastname, city, state, birth_date, dl_state) %>%
        mutate(
          # Hunter key per individual (not per row)
          hunter_key = cur_group_id(),
          # Find the reason for the duplicates
          # We start with a blank string so the following code can paste in
          dupl = "",
          # Iterate over each field in order to paste the field names together
          # (can't be done with case_when)
          dupl =
            ifelse(
              length(unique(title)) > 1,
              paste(dupl, "title", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(middle)) > 1,
              paste(dupl, "middle", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(suffix)) > 1,
              paste(dupl, "suffix", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(address)) > 1,
              paste(dupl, "address", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(zip)) > 1,
              paste(dupl, "zip", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(birth_date)) > 1,
              paste(dupl, "birth_date", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(issue_date)) > 1,
              paste(dupl, "issue_date", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(hunt_mig_birds)) > 1,
              paste(dupl, "hunt_mig_birds", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(registration_yr)) > 1,
              paste(dupl, "registration_yr", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(email)) > 1,
              paste(dupl, "email", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(dl_date)) > 1,
              paste(dupl, "dl_date", sep = "-"),
              dupl),
          dupl =
            ifelse(
              length(unique(dl_cycle)) > 1,
              paste(dupl, "dl_cycle", sep = "-"),
              dupl),
          dupl = ifelse(str_detect(dupl, "^$"), "bag", dupl),
          dupl = str_remove(dupl, "^\\-")
        ) %>%
        ungroup() %>%
        select(hunter_key, dupl) %>%
        distinct() %>%
          # Bin into generic "2+ fields" if more than one field contributes to a
          # duplicate
          mutate(
            dupl =
              case_when(
                str_detect(dupl, "[a-z|a-z\\_a-z|a-z|a-z\\_a-z\\_a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}") ~ "2+ fields", #5+ fields
                str_detect(dupl, "[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}") ~ "2+ fields", #4 fields
                str_detect(dupl, "[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}") ~ "2+ fields", #3 fields
                str_detect(dupl, "[a-z|a-z\\_a-z]{1,}\\-[a-z|a-z\\_a-z]{1,}") ~ "2+ fields",
                TRUE ~ dupl)
          ) %>%
          # Make a new col to reorder the bars
          group_by(dupl) %>%
          mutate(total_count = n()) %>%
          ungroup() %>%
          ggplot(aes(x = reorder(dupl, -total_count))) +
          geom_bar(stat = "count") +
          geom_text(
            aes(
              x = dupl,
              label = stat(count),
              angle = 90),
            stat = "count",
            vjust = 0.2,
            hjust = -0.2) +
          labs(
            x = "Inconsistent field(s) for duplicated hunters",
            y = "Count",
            title = "Types of duplicates") +
          scale_y_continuous(expand = expansion(mult = c(-0, 0.2))) +
          theme_classic() +
          theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
        
      
    })
  },

  options = list(height = 500)
)
```
