#' Fail if non-proofed data frame supplied
#'
#' Internal function that fails if a tibble without \code{errors} field
#' (generated by \code{\link{proof}}) is provided.
#'
#' @importFrom assertthat assert_that
#'
#' @param proofed_data The object created after error flagging data with
#'   \code{\link{proof}}
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failProofed <-
  function(proofed_data) {
    assert_that(
      "errors" %in% names(proofed_data), msg = "`errors` field not in data.")
  }

#' Fail if bad state abbreviation supplied
#'
#' Internal function that fails if a bad state abbreviation is provided.
#'
#' @importFrom assertthat assert_that
#'
#' @param state Any abbreviation for one of the 49 contiguous states:
#' \itemize{
#' \item `r REF_ABBR_49_STATES`}
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failState <-
  function(state) {
    assert_that(
      state %in% REF_ABBR_49_STATES,
      msg =
        paste0(
          "`state` one of acceptable state abbreviations: ",
          REF_ABBR_49_STATES, ".")
    )
  }

#' Fail if TRUE or FALSE is not supplied
#'
#' Internal function that fails if something other than TRUE or FALSE is
#' supplied.
#'
#' @importFrom assertthat assert_that
#'
#' @param TF Must be TRUE, FALSE, T, or F
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failTF <-
  function(TF) {
    assert_that(
      TF %in% c(TRUE, FALSE, T, F),
      msg = "param not TRUE, FALSE, T, or F.")
  }

#' Fail if incorrect year supplied
#'
#' Internal function that fails if an incorrect year is provided.
#'
#' @importFrom assertthat assert_that
#' @importFrom rlang is_integerish
#'
#' @param year The year in which the Harvest Information Program data were
#'   collected
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failYear <-
  function(year) {
    assert_that(
      is_integerish(year),
      year >= 2020,
      year <= REF_CURRENT_SEASON,
      msg =
        paste0(
          "`year` must be a whole number between 2020 and ",
          REF_CURRENT_SEASON,
          "."
        )
    )
  }

#' Fail if BTPI permit file contains bad values
#'
#' Internal function that applies to BTPI permit files.
#'
#' @param corrected_data The object created after correcting data with
#'   \code{\link{correct}}
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failBTPI <-
  function(corrected_data) {
    # Fail if BT permit file does not contain record_type = HIP
    stopifnot(
      "Error: BTPI permit files must contain record_type = HIP." =
        unique(corrected_data$record_type) == "HIP")

    # Fail if BT permit file does not contain 2 for BT
    stopifnot(
      "Error: BTPI permit files must contain band_tailed_pigeon = 2." =
        unique(corrected_data$band_tailed_pigeon) == "2")

    # Warn if BT permit file contains any 0s for DV
    if (0 %in% unique(corrected_data$dove_bag)) {
      message("Warning: BTPI permit file contains dove_bag == 0.")
    }

    # Fail if BT permit file does not contain non-0 values for DV
    stopifnot(
      "Error: BTPI permit files must have values other than 0 in dove_bag." =
        length(unique(corrected_data$dove_bag)) > 1)

    # Fail if any bag field other than BT or DV is not 0
    stopifnot(
      "Error: Ducks bag must be 0 in BTPI permit files." =
        unique(corrected_data$ducks_bag) == 0)
    stopifnot(
      "Error: Geese bag must be 0 in BTPI permit files." =
        unique(corrected_data$geese_bag) == 0)
    stopifnot(
      "Error: Woodcock bag must be 0 in BTPI permit files." =
        unique(corrected_data$woodcock_bag) == 0)
    stopifnot(
      "Error: Coots_snipe bag must be 0 in BTPI permit files." =
        unique(corrected_data$coots_snipe) == 0)
    stopifnot(
      "Error: Rails_gallinules bag must be 0 in BTPI permit files." =
        unique(corrected_data$rails_gallinules) == 0)
    stopifnot(
      "Error: Cranes bag must be 0 in BTPI permit files." =
        unique(corrected_data$cranes) == 0)
    stopifnot(
      "Error: Brant bag must be 0 in BTPI permit files." =
        unique(corrected_data$brant) == 0)
    stopifnot(
      "Error: Sea ducks bag must be 0 in BTPI permit files." =
        unique(corrected_data$seaducks) == 0)
  }

#' Fail if crane permit file contains bad values
#'
#' Internal function that applies to crane permit files.
#'
#' @param corrected_data The object created after correcting data with
#'   \code{\link{correct}}
#'
#' @author Abby Walter, \email{abby_walter@@fws.gov}
#' @references \url{https://github.com/USFWS/migbirdHIP}

failCR <-
  function(corrected_data) {
    # Fail if CR permit file does not contain record_type = PMT
    stopifnot(
      "Error: CR permit files must contain record_type = PMT." =
        unique(corrected_data$record_type) == "PMT")

    # Fail if CR permit file does not contain 2 for CR
    stopifnot(
      "Error: CR permit files must contain cranes = 2." =
        unique(corrected_data$cranes) == "2")

    # Fail if any bag field other than CR is not 0
    stopifnot(
      "Error: Ducks bag must be 0 in CR permit files." =
        unique(corrected_data$ducks_bag) == 0)
    stopifnot(
      "Error: Geese bag must be 0 in CR permit files." =
        unique(corrected_data$geese_bag) == 0)
    stopifnot(
      "Error: Dove bag must be 0 in CR permit files." =
        unique(corrected_data$dove_bag) == 0)
    stopifnot(
      "Error: Woodcock bag must be 0 in CR permit files." =
        unique(corrected_data$woodcock_bag) == 0)
    stopifnot(
      "Error: Coots_snipe bag must be 0 in CR permit files." =
        unique(corrected_data$coots_snipe) == 0)
    stopifnot(
      "Error: Rails_gallinules bag must be 0 in CR permit files." =
        unique(corrected_data$rails_gallinules) == 0)
    stopifnot(
      "Error: Band tailed pigeon bag must be 0 in CR permit files." =
        unique(corrected_data$band_tailed_pigeon) == 0)
    stopifnot(
      "Error: Brant bag must be 0 in CR permit files." =
        unique(corrected_data$brant) == 0)
    stopifnot(
      "Error: Sea ducks bag must be 0 in CR permit files." =
        unique(corrected_data$seaducks) == 0)
  }
